### ISSUE TITLE
Error when trying to contact the OLS

### ISSUE THREAD

**Issue by Geize** [PRIDE-Archive/px-submission-tool#132]
Hi there, 

Could you please let me know why I have been getting this warning?

thanks.

<img width="738" alt="Captura de Tela 2022-05-23 às 22 55 23" src="https://user-images.githubusercontent.com/7786478/169905009-67bfc6be-ebcc-499c-9bf2-d7b95dbf9cf6.png">

**Comment by ypriverol** [comment]
@Geize @KR-15 I have solve the issue. We will release a new version.

**Comment by ypriverol** [comment]
Solved in release https://github.com/PRIDE-Archive/px-submission-tool/releases/download/2.5.5/px-submission-tool-2.5.5.zip

**Comment by 1364048792** [comment]
Same issue for the latest version of px-submission tool, dude. It is still not fixed. I am gonna upload dog brain proteome data, but Term ID search failed.
![image](https://user-images.githubusercontent.com/107016030/172284479-d06325e4-46a1-4ed1-bfaf-a4eeb4de333b.png)
